name: gnome-extra/nemo-python update

on:
  workflow_dispatch: # manual trigger
  # schedule:
  #   - cron: "0 3 * * *"
  push:
    branches: [main]
    paths:
      - '.github/workflows/gnome-extra-nemo-python-update.yaml'
      - 'gnome-extra/nemo-python/**'
      - 'scripts/gnome-extra/nemo-python/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/gnome-extra-nemo-python-update.yaml'
      - 'gnome-extra/nemo-python/**'
      - 'scripts/gnome-extra/nemo-python/**'

env:
  ECN: gnome-extra
  EPN: nemo-python

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      changed: ${{ steps.update_script.outputs.changed }}
    steps:
      - name: Checkout overlay repo
        uses: actions/checkout@v5

      - name: Set up git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run update script
        id: update_script
        run: scripts/update-manifest-simple.sh

  pkgcheck:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-pkgcheck-${{ github.ref }}
      cancel-in-progress: true
    needs: update
    if: ${{ needs.update.outputs.changed == '1' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Pull latest changes
        run: git pull

      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1

      - name: Handle cancellation
        if: ${{ cancelled() }}
        continue-on-error: true
        run: |
          echo "Job was cancelled - pkgcheck will be run by a newer job"
          # Exit successfully when cancelled
          exit 0
