name: sci-ml/ollama update

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [main, distfiles]
    paths:
      - '.github/workflows/sci-ml-ollama-update.yaml' 
      - 'sci-ml/ollama/**' 
  pull_request:
    branches: [main, distfiles]
    paths:
      - '.github/workflows/sci-ml-ollama-update.yaml'
      - 'sci-ml/ollama/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

env:
  ecn: sci-ml
  epn: ollama

jobs:
  release-status:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
      version: ${{ steps.get_tag.outputs.version }}
      new: ${{ steps.requirements.outputs.new }}
    steps:
      - name: Get latest Ollama release tag
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq -r .tag_name)
          LATEST_VERSION=$(echo "$LATEST_TAG" | sed 's/^v//')
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Checkout overlay repo
        uses: actions/checkout@v5

      - name: Check build requirements
        id: requirements
        run: |
          if [ -f "${{ env.ecn }}/${{ env.epn }}/${{ env.epn }}-${{ steps.get_tag.outputs.version }}.ebuild" ]; then
            echo "new=false" >> "$GITHUB_OUTPUT"
          else
            echo "new=true" >> "$GITHUB_OUTPUT"
          fi

  build-vendor-tarball:
    runs-on: ubuntu-latest
    needs: release-status
    if: ${{ needs.release-status.outputs.new == 'true' }}
    permissions:
      contents: write
    steps:
      - name: Checkout overlay repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # needed to push to distfiles branch

      - name: Set up git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Clone Ollama
        run: |
          git clone --depth 1 --branch "${{ needs.release-status.outputs.tag }}" https://github.com/ollama/ollama.git ${{ env.epn }}-${{ needs.release-status.outputs.version }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.epn }}-${{ needs.release-status.outputs.version }}/go.mod
          cache: false

      - name: Vendor dependencies
        working-directory: ${{ env.epn }}-${{ needs.release-status.outputs.version }}
        run: |
          go mod tidy
          go mod vendor

      - name: Create vendor tarball
        run: |
          tar -caf "${{ env.epn }}-${{ needs.release-status.outputs.version }}-vendor.tar.xz" ${{ env.epn }}-${{ needs.release-status.outputs.version }}/vendor

      - name: Switch to distfiles branch
        run: |
          git checkout distfiles || git switch --orphan distfiles

      - name: Move tarball into correct location
        run: |
          mkdir -p ${{ env.ecn }}/${{ env.epn }}
          mv "${{ env.epn }}-${{ needs.release-status.outputs.version }}-vendor.tar.xz" ${{ env.ecn }}/${{ env.epn }}/

      - name: Commit and push changes
        run: |
          git add ${{ env.ecn }}/${{ env.epn }}/${{ env.epn }}-${{ needs.release-status.outputs.version }}-vendor.tar.xz
          git commit -m "Add vendor distfiles for new ${{ env.ecn }}/${{ env.epn }} releases tag ${{ needs.release-status.outputs.tag }}" &&
          git push origin distfiles

  create-ebuild:
    runs-on: ubuntu-latest
    needs: [release-status, build-vendor-tarball]
    if: ${{ needs.release-status.outputs.new == 'true' }}
    permissions:
      contents: write
    steps:
      - name: Checkout overlay repo
        uses: actions/checkout@v5

      - name: Set up git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create ebuild
        run: |
          cp ${{ env.ecn }}/${{ env.epn }}/${{ env.epn }}-9999.ebuild ${{ env.ecn }}/${{ env.epn }}/${{ env.epn }}-${{ needs.release-status.outputs.version }}.ebuild

      - name: Generate manifest
        run: |
          g2 manifest upsert-from-url "https://github.com/ollama/${{ env.epn }}/archive/refs/tags/v${{ needs.release-status.outputs.version }}.tar.gz" "${{ env.epn }}-${{ needs.release-status.outputs.version }}.gh.tar.gz" "${{ env.ecn }}/${{ env.epn }}/Manifest"
          g2 manifest upsert-from-url "https://github.com/lmarzen/gentoo-overlay/raw/refs/heads/distfiles/${{ env.ecn }}/${{ env.epn }}/${{ env.epn }}-${{ needs.release-status.outputs.version }}-vendor.tar.xz" "${{ env.ecn }}/${{ env.epn }}/Manifest"

      - name: Commit and push changes
        run: |
          git add ./${{ env.ecn }}/${{ env.epn }}/${{ env.epn }}-${{ needs.release-status.outputs.version }}.ebuild
          git add ./${{ env.ecn }}/${{ env.epn }}/Manifest
          git commit -m "Add ebuild for new ${{ env.ecn }}/${{ env.epn }} releases tag ${{ needs.release-status.outputs.tag }}" &&
          git push || true

  pkgcheck:
    runs-on: ubuntu-latest
    needs: regenerate-manifests
    if: always()
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
