name: sci-ml/ollama update

permissions:
  contents: write

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - '.github/workflows/sci-ml-ollama-update.yaml' 

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

env:
  ecn: sci-ml
  epn: ollama

jobs:
  release-status:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
      version: ${{ steps.get_tag.outputs.version }}
      new: ${{ steps.requirements.outputs.new }}
    steps:
      - name: Get latest Ollama release tag
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq -r .tag_name)
          LATEST_VERSION=$(echo "$LATEST_TAG" | sed 's/^v//')
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Checkout overlay repo
        uses: actions/checkout@v4

      - name: Check build requirements
        id: requirements
        run: |
          if [ -f "${{ env.ecn }}/${{ env.epn }}-${{ steps.get_tag.version }}.ebuild" ]; then
            echo "new=true" >> "$GITHUB_OUTPUT"
          else
            echo "new=false" >> "$GITHUB_OUTPUT"
          fi

  build-vendor-tarball:
    runs-on: ubuntu-latest
    needs: release-status
    if: needs.release-status.new == 'true'
    steps:
      - name: Checkout overlay repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to push to distfiles branch

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Clone Ollama
        run: |
          git clone --depth 1 --branch "${{ needs.release-status.tag }}" https://github.com/ollama/ollama.git ${{ env.epn }}-${{ needs.release-status.version }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.epn }}-${{ needs.release-status.version }}/go.mod
          cache: false

      - name: Vendor dependencies
        working-directory: ${{ env.epn }}-${{ needs.release-status.version }}
        run: |
          go mod tidy
          go mod vendor

      - name: Create vendor tarball
        run: |
          tar -caf "${{ env.epn }}-${{ needs.release-status.version }}-vendor.tar.xz" ${{ env.epn }}-${{ needs.release-status.version }}/vendor

      - name: Switch to distfiles branch
        run: |
          git checkout distfiles || git switch --orphan distfiles

      - name: Move tarball into correct location
        run: |
          mkdir -p ${{ env.ecn }}
          mv "${{ env.epn }}-${{ needs.release-status.version }}-vendor.tar.xz" ${{ env.ecn }}/

      - name: Commit and push changes
        run: |
          git add ${{ env.ecn }}/${{ env.epn }}-${{ needs.release-status.version }}-vendor.tar.xz
          git commit -m "Add vendor distfiles for new ${{ env.ecn }}/${{ env.epn }} releases tag ${{ needs.release-status.tag }}" &&
          git push origin distfiles

  create-ebuild:
    runs-on: ubuntu-latest
    needs: build-vendor-tarball
    if: needs.release-status.new == 'true'
    steps:
      - name: Checkout overlay repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create ebuild
        run: |
          pwd
          ls
          cp ${{ env.ecn }}/${{ env.epn }}-9999.ebuild ${{ env.ecn }}/${{ env.epn }}-${{ needs.release-status.version }}.ebuild

      - name: Commit and push changes
        run: |
          git add ./${{ env.ecn }}/${{ env.epn }}-${{ needs.release-status.version }}.ebuild
          git commit -m "Add ebuild for new ${{ env.ecn }}/${{ env.epn }} releases tag ${{ needs.release-status.tag }}" &&
          git push
